#!/bin/bash
#
#	/etc/init.d/mydaemon
#
# Starts the at mydaemon
#
# chkconfig: 345 95 5
# description: Runs the demonstration mydaemon.
# processname: mydaemon
 
# Source function library.
. /lib/lsb/init-functions 
#startup values
 
#verify that the executable exists
phpfile=/var/www/mydaemon.php
test -x $phpfile || exit 0RETVAL=0
 
#
#	Set prog, proc and bin variables.
#
prog="mydaemon"
proc=/var/run/mydaemon
bin=/usr/bin/php
 
start() {
	# Check if Daemon is already running
	if [ ! -f $proc ]; then
	    echo -n $"Starting $prog: "
	    start-stop-daemon --start --exec $bin -- $phpfile
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch $proc
	    echo
	fi
 
	return $RETVAL
}
 
stop() {
	echo -n $"Stopping $prog: "
	start-stop-daemon --stop --exec $bin -- $phpfile
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $proc
	echo
        return $RETVAL
}
 
restart() {
	stop
	start
}	
 
reload() {
	restart
}	
 
status_at() {
 	status $bin
}
 
case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload|restart)
	restart
	;;
condrestart)
        if [ -f $proc ]; then
            restart
        fi
        ;;
status)
	status_at
	;;
*)
 
echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	exit 1
esac
 
exit $?
exit $RETVAL
